# Generated by Django 2.2.4 on 2020-03-27 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='详情介绍')),
                ('pic_index', models.TextField(blank=True, null=True, verbose_name='标题图')),
                ('nine_pics', models.TextField(blank=True, null=True, verbose_name='九宫格')),
                ('all_pics', models.TextField(blank=True, null=True, verbose_name='所有图')),
                ('is_delete', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('praise_count', models.IntegerField(default=1, verbose_name='点赞数')),
                ('browse_count', models.IntegerField(default=1, verbose_name='浏览量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type_one', models.ManyToManyField(to='personal.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
    ]
